version: 2
project_name: dt-task
builds:
  - main: ./cmd/dt-task
    binary: dt-task
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/deepaktiwari09/dt-task-cli/internal/cli.version={{.Version}}
    env: [CGO_ENABLED=0]
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.json"
release:
  prerelease: auto
